### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by OmgImAlexis** [brohrer/brohrer.github.io#2]
You currently have mixed content issues with this repo because of `kdnuggets.com`, currently their SSL cert is 637 days out of date and needs renewing. Once that's fixed you can change all the `http://kdnuggets.com` referances to `https://kdnuggets.com`. For now I'd suggest maybe uploading the images to this repo or using a free service like imgur to host the images.

For example LN64 in blog.html

```
<img src="http://www.kdnuggets.com/images/top-kdnuggets-blogger-2016-sep-gold.jpg" width=90 height=90 alt="Top KDnuggets Blogger - Gold, September 2016">
```

Ref: https://twitter.com/OmgImAlexis/status/780592227454156800

**Comment by brohrer** [comment]
Thanks @OmgImAlexis. I wasn't aware of this issue at all. I went through and made local copies of these images on this github repo. I believe it's all resolved.
